#!/bin/bash
set -euo pipefail

# needed for nx watch mode: https://github.com/lerna/lerna/issues/4054#issuecomment-2598693480
export NX_DAEMON=true
export PROJECT_NAME=$(jq -r '.name' package.json)
pnpm nx watch --includeDependentProjects --projects $PROJECT_NAME -- shx run/build
