#!/bin/bash
set -euo pipefail

# TODO: centralize these variable
export ARCH=$(dpkg --print-architecture)

# TODO: use .shxrc
export DOCKER_TAG="ghcr.io/appcited/weeker/shell-app:main-${ARCH}"

mkdir -p pack
docker build \
    --build-arg NODE_VERSION="${NODE_VERSION}" \
    --build-arg PNPM_VERSION="${PNPM_VERSION}" \
    --tag "${DOCKER_TAG}" .
docker image save "${DOCKER_TAG}" | gzip > pack/shell-app.tar.gz
