#!/bin/bash
set -euo pipefail

# TODO: centralize these variable
export ARCH=$(dpkg --print-architecture)

# TODO: use .shxrc
# TODO: use multi-arch build
export DOCKER_TAG="ghcr.io/appcited/weeker/api:main-${ARCH}"

docker load < pack/api.tar.gz
docker push "${DOCKER_TAG}"
