#!/bin/bash
set -euo pipefail

# needed for nx watch mode: https://github.com/lerna/lerna/issues/4054#issuecomment-2598693480
export NX_DAEMON=true
npx nx watch --includeDependentProjects --projects @weeker/shared-logo -- npx nx run @weeker/shared-logo:build
