#!/bin/bash
set -euo pipefail

# needed for nx watch mode: https://github.com/lerna/lerna/issues/4054#issuecomment-2598693480
export NX_DAEMON=true
pnpm nx watch --all --includeDependentProjects -- pnpm nx run-many -t ci --output-style stream
