#!/bin/bash
set -euo pipefail

# TODO: centralize these variable
export ARCH=$(dpkg --print-architecture)

# TODO: use .shxrc
# TODO: use multi-arch build
export DOCKER_TAG="ghcr.io/appcited/weeker/app:main-${ARCH}"

docker load < pack/app.tar.gz
docker push "${DOCKER_TAG}"
