name: main
on:
  push:
    branches:
      - main
jobs:
  main:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform:
          - name: amd64
            os: ubuntu-24.04
          - name: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/appcited/weeker/devcontainer
          imageTag: latest-${{ matrix.platform.name }}
          cacheFrom: ghcr.io/appcited/weeker/devcontainer:latest-${{ matrix.platform.name }}
          push: always
          runCmd: |
            shx run/ci
